### ISSUE TITLE
Is masking implemented?

### ISSUE THREAD

**Issue by kevinpeterson** [dannyneil/pytorch_plstm#2]
Is masking actually being used? I see it referenced here:

https://github.com/dannyneil/pytorch_plstm/blob/96cc3b6f02d298cac433e1c479fb03ba41b824df/main.py#L105

but does it actually get used or have any impact?

**Comment by dannyneil** [comment]
Thanks for asking.  No, it was used in the [original code](https://github.com/dannyneil/public_plstm) but I did not reimplement here.
